linters:
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default

  # Enable only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true
  disable:
   - depguard

run:
  tests: false
